
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define VIAL_KEYBOARD_UID {0xDF, 0x91, 0x77, 0xF7, 0xA7, 0xCD, 0x50, 0xEE}

// #define POINTING_DEVICE_DEBUG
#define ANALOG_JOYSTICK_X_AXIS_PIN F6
#define ANALOG_JOYSTICK_Y_AXIS_PIN F7
#define ANALOG_JOYSTICK_SPEED_REGULATOR 10


// 搖桿位置一
// #define POINTING_DEVICE_INVERT_X

// 搖桿位置二
// #define POINTING_DEVICE_INVERT_Y
